
# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://live-interfaces.github.io/liveinterfaces2020'
baseurl: 'liveinterfaces2020'
title: 'ICLI 2020 Trondheim'
description: 'International Conference on Live Interfaces, March 9-11 2020, Trondheim Norway'
permalink: pretty


# Header nav
navigation_header:
  Home: /
  Call: /cfp/
  Organization: /organization/

# Footer nav
navigation_footer:
  Back to top: "#top"

