
# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://live-interfaces.github.io/'
baseurl: '/'
title: 'ICLI 2020 Trondheim'
description: 'International Conference on Live Interfaces, March 9-11 2020, Trondheim Norway'
permalink: pretty


# Header nav
navigation_header:
  - title: Home
    url: /
  - title: Program 
    url: /program/
  - title: Travel and participation
    url: /trondheim/
  - title: Organization 
    url: /organization/
  - title: Proceedings 
    url: /proceedings/
  - title: About 
    url: /about/

  # - title: Call
    # url: /cfp/
  # - title: Open call
    # url: /interfaces/

# Footer nav
navigation_footer:
  Back to top: "#top"
