theme: jekyll-theme-slate
title: ICLI 2020 Trondheim
description: International Conference on Live Interfaces, March 9-11 2020, Trondheim Norway
markdown: kramdown
#baseurl: ""
#url: "http://www.liveinterfaces.org/"
github: [metadata] 
